### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Farolina**

### CODE REVIEW

**Review by Mansafreo — CHANGES_REQUESTED** [review]
This is way too much for now. We just need a functional menu. This is  because we'd still need to merge many other functions so adding many functions together isn't advisable in my opinion. But this is still great. It'll help us with later functionality. Keep a copy of this. But just the menu will do for now

**Comment by Farolina** [comment]
Noted i will send just the menu nowFirdausOn 4 Jan 2023, at 12:31 AM, Mansafreo ***@***.***> wrote:﻿
@Mansafreo requested changes on this pull request.

This is way too much for now. We just need a functional menu. This is  because we'd still need to merge many other functions so adding many functions together isn't advisable in my opinion. But this is still great. It'll help us with later functionality. Keep a copy of this. But just the menu will do for now

**Comment by Farolina** [comment]
> This is way too much for now. We just need a functional menu. This is because we'd still need to merge many other functions so adding many functions together isn't advisable in my opinion. But this is still great. It'll help us with later functionality. Keep a copy of this. But just the menu will do for now

Noted.

**Review by Mansafreo — COMMENTED** [review]
Thanks for the changes. Awesome work on the menu. Now this is what we needed. It will make designing the rest simple

**Review by Mansafreo — APPROVED** [review]

**Review by darcishED — APPROVED** [review]

**Pull request merged**
